-- LightBot 2.1.0 init SQL
-- Generated by merging sql/*.sql through 2026-07-21.

-- ============================================================================
-- Base schema source merged into the v2.1.0 snapshot
-- ============================================================================

-- ============================================================
-- LightBot Database Initialization (Complete)
-- PostgreSQL 15 + pgvector
-- 合并日期：2026-06-18
-- 包含 v2.1.0 的最终结构；存量环境升级请执行后续增量迁移文件
-- ============================================================

CREATE DATABASE lightbot ENCODING 'UTF8';
\c lightbot;

CREATE EXTENSION IF NOT EXISTS vector;

-- ========================================
-- 用户表（user 为PG保留字，使用 users）
-- ========================================
CREATE TABLE users (
    id              BIGINT          NOT NULL,
    username        VARCHAR(64)     NOT NULL,
    email           VARCHAR(128)    DEFAULT '',
    password        VARCHAR(256)    NOT NULL,
    nickname        VARCHAR(64),
    avatar          VARCHAR(512),
    phone           VARCHAR(20),
    role            VARCHAR(20)     NOT NULL DEFAULT 'user',
    status          VARCHAR(20)     NOT NULL DEFAULT 'active',
    last_login_at   TIMESTAMP,
    config          JSONB           DEFAULT '{}',
    create_time     TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time     TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted         SMALLINT        NOT NULL DEFAULT 0,
    PRIMARY KEY (id)
);
CREATE UNIQUE INDEX uk_user_username ON users (username) WHERE deleted = 0;
CREATE INDEX idx_user_status ON users (status);
CREATE INDEX idx_user_create_time ON users (create_time);
COMMENT ON TABLE users IS '用户表';

-- ========================================
-- 模型提供商表
-- ========================================
CREATE TABLE model_provider (
    id              BIGINT          NOT NULL,
    name            VARCHAR(64)     NOT NULL,
    type            VARCHAR(32)     NOT NULL,
    api_key         VARCHAR(512),
    base_url        VARCHAR(256),
    config          JSONB           DEFAULT '{}',
    status          VARCHAR(20)     NOT NULL DEFAULT 'active',
    models_endpoint VARCHAR(512),
    headers_json    JSONB           DEFAULT '{}',
    extra_json      JSONB           DEFAULT '{}',
    create_time     TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time     TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted         SMALLINT        NOT NULL DEFAULT 0,
    PRIMARY KEY (id)
);
CREATE INDEX idx_model_provider_type ON model_provider (type);
CREATE INDEX idx_model_provider_status ON model_provider (status);
COMMENT ON TABLE model_provider IS '模型提供商表';
COMMENT ON COLUMN model_provider.models_endpoint IS '模型列表获取地址（为空时使用默认地址）';
COMMENT ON COLUMN model_provider.headers_json IS '额外请求头（JSON格式）';
COMMENT ON COLUMN model_provider.extra_json IS '扩展配置（JSON格式）';

-- ========================================
-- 模型表
-- ========================================
CREATE TABLE model (
    id              BIGINT          NOT NULL,
    provider_id     BIGINT          NOT NULL,
    model_id        VARCHAR(128)    NOT NULL,
    name            VARCHAR(128)    NOT NULL,
    type            VARCHAR(20)     NOT NULL DEFAULT 'llm',
    status          VARCHAR(20)     NOT NULL DEFAULT 'active',
    create_time     TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time     TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted         SMALLINT        NOT NULL DEFAULT 0,
    PRIMARY KEY (id)
);
CREATE INDEX idx_model_provider_id ON model (provider_id);
CREATE INDEX idx_model_type ON model (type);
COMMENT ON TABLE model IS '模型表';

-- ========================================
-- Agent 表
-- ========================================
CREATE TABLE agent (
    id              BIGINT          NOT NULL,
    user_id         BIGINT          NOT NULL,
    name            VARCHAR(128)    NOT NULL,
    description     TEXT,
    system_prompt   TEXT,
    avatar          VARCHAR(512),
    icon            VARCHAR(32),
    agent_type      VARCHAR(32)     NOT NULL DEFAULT 'chat',
    config          JSONB           DEFAULT '{}',
    status          VARCHAR(20)     NOT NULL DEFAULT 'draft',
    publish_time    TIMESTAMP,
    version         INT             NOT NULL DEFAULT 1,
    welcome_message TEXT,
    recommended_questions JSONB,
    is_default      BOOLEAN         NOT NULL DEFAULT FALSE,
    create_time     TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time     TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted         SMALLINT        NOT NULL DEFAULT 0,
    PRIMARY KEY (id)
);
CREATE INDEX idx_agent_user_id ON agent (user_id);
CREATE INDEX idx_agent_status ON agent (status);
CREATE INDEX idx_agent_create_time ON agent (create_time);
COMMENT ON TABLE agent IS 'Agent表';
COMMENT ON COLUMN agent.icon IS 'Agent图标（emoji或图标标识）';
COMMENT ON COLUMN agent.welcome_message IS '欢迎语';
COMMENT ON COLUMN agent.recommended_questions IS '推荐问题列表';

-- ========================================
-- Agent 版本配置表
-- ========================================
CREATE TABLE agent_version (
    id              BIGINT          NOT NULL,
    agent_id        BIGINT          NOT NULL,
    user_id         BIGINT          NOT NULL,
    version         INT             NOT NULL DEFAULT 0,
    status          VARCHAR(32)     NOT NULL DEFAULT 'draft',
    config          JSONB           NOT NULL DEFAULT '{}',
    node_count      INT             NOT NULL DEFAULT 0,
    edge_count      INT             NOT NULL DEFAULT 0,
    description     VARCHAR(512),
    publish_time    TIMESTAMP,
    create_time     TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time     TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted         SMALLINT        NOT NULL DEFAULT 0,
    PRIMARY KEY (id)
);
CREATE INDEX idx_agent_version_agent_id ON agent_version (agent_id);
CREATE INDEX idx_agent_version_agent_status ON agent_version (agent_id, status);
CREATE UNIQUE INDEX uk_agent_version_agent_pub ON agent_version (agent_id, version)
    WHERE status = 'published' AND deleted = 0;
COMMENT ON TABLE agent_version IS 'Agent版本配置表（草稿与发布历史）';
COMMENT ON COLUMN agent_version.version IS '发布版本号，草稿行为0';
COMMENT ON COLUMN agent_version.status IS 'draft=当前草稿 published=已发布历史版本';
COMMENT ON COLUMN agent_version.config IS '版本快照JSON（workflow图或对话配置）';

-- ========================================
-- SubAgent 表
-- ========================================
CREATE TABLE subagent (
    id                      BIGINT          NOT NULL,
    name                    VARCHAR(128)    NOT NULL UNIQUE,
    display_name            VARCHAR(128)    NOT NULL,
    description             TEXT            NOT NULL,
    system_prompt           TEXT            NOT NULL,
    tool_ids                JSONB           NOT NULL DEFAULT '[]',
    model_id                BIGINT,
    llm_model               VARCHAR(128),
    connect_timeout_seconds INTEGER         NOT NULL DEFAULT 10,
    read_timeout_seconds    INTEGER         NOT NULL DEFAULT 45,
    model_retry_times       INTEGER         NOT NULL DEFAULT 1,
    enabled                 SMALLINT        NOT NULL DEFAULT 1,
    is_builtin              SMALLINT        NOT NULL DEFAULT 0,
    icon                    VARCHAR(64),
    user_id                 BIGINT,
    create_time             TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time             TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted                 SMALLINT        NOT NULL DEFAULT 0,
    PRIMARY KEY (id)
);
CREATE INDEX idx_subagent_name ON subagent (name);
CREATE INDEX idx_subagent_enabled ON subagent (enabled);
CREATE INDEX idx_subagent_is_builtin ON subagent (is_builtin);
COMMENT ON TABLE subagent IS '子智能体配置表';
COMMENT ON COLUMN subagent.name IS '唯一标识（英文）';
COMMENT ON COLUMN subagent.display_name IS '显示名称（中文）';
COMMENT ON COLUMN subagent.description IS '子智能体描述';
COMMENT ON COLUMN subagent.system_prompt IS '系统提示词';
COMMENT ON COLUMN subagent.tool_ids IS '绑定工具ID列表（JSON数组）';
COMMENT ON COLUMN subagent.model_id IS '可选的 Provider ID 覆盖，null 表示继承主 Agent';
COMMENT ON COLUMN subagent.llm_model IS '可选的模型名称覆盖（如 gpt-4o），与 model_id 配合使用';
COMMENT ON COLUMN subagent.connect_timeout_seconds IS 'SubAgent 模型连接超时（秒），默认 10';
COMMENT ON COLUMN subagent.read_timeout_seconds IS 'SubAgent 整体响应超时（秒），默认 45';
COMMENT ON COLUMN subagent.model_retry_times IS 'SubAgent 模型调用失败重试次数，默认 1（即最多再试 1 次）';
COMMENT ON COLUMN subagent.enabled IS '是否启用';
COMMENT ON COLUMN subagent.is_builtin IS '是否内置';
COMMENT ON COLUMN subagent.icon IS '图标标识（Ant Design 图标组件名）';
COMMENT ON COLUMN subagent.user_id IS '创建者ID';

-- ========================================
-- 对话会话表
-- ========================================
CREATE TABLE chat_session (
    id              BIGINT          NOT NULL,
    agent_id        BIGINT,
    user_id         BIGINT          NOT NULL,
    title           VARCHAR(256),
    status          VARCHAR(20)     NOT NULL DEFAULT 'active',
    source          VARCHAR(20)     NOT NULL DEFAULT 'platform',
    api_key_id      BIGINT          NULL,
    external_user_id VARCHAR(128)   NULL,
    context         JSONB           DEFAULT '{}',
    message_count   INT             NOT NULL DEFAULT 0,
    total_tokens    BIGINT          NOT NULL DEFAULT 0,
    last_message_at TIMESTAMP,
    pinned          BOOLEAN         NOT NULL DEFAULT FALSE,
    attachments     JSONB,
    create_time     TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time     TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted         SMALLINT        NOT NULL DEFAULT 0,
    PRIMARY KEY (id)
);
CREATE INDEX idx_chat_session_agent_id ON chat_session (agent_id);
CREATE INDEX idx_chat_session_user_id ON chat_session (user_id);
CREATE INDEX idx_chat_session_status ON chat_session (status);
CREATE INDEX idx_chat_session_last_message ON chat_session (last_message_at DESC);
CREATE INDEX idx_chat_session_pinned ON chat_session (user_id, pinned DESC, last_message_at DESC);
CREATE INDEX idx_chat_session_source ON chat_session (source);
CREATE INDEX idx_chat_session_api_key_id ON chat_session (api_key_id);
CREATE INDEX idx_chat_session_api_external ON chat_session (api_key_id, external_user_id)
    WHERE external_user_id IS NOT NULL;
COMMENT ON TABLE chat_session IS '对话会话表';
COMMENT ON COLUMN chat_session.source IS '会话来源：platform=平台调试，api=企业API Key集成，automation=自动化';
COMMENT ON COLUMN chat_session.api_key_id IS '企业 API Key ID（source=api 时有值）';
COMMENT ON COLUMN chat_session.external_user_id IS '上层业务系统终端用户标识（source=api 时可选）';
COMMENT ON COLUMN chat_session.attachments IS '会话附件索引 JSON 数组（source: user_upload|ai_image|ai_sandbox|ai_deliver）';

-- ========================================
-- 消息表
-- ========================================
CREATE TABLE message (
    id              BIGINT          NOT NULL,
    session_id      BIGINT          NOT NULL,
    role            VARCHAR(20)     NOT NULL,
    content         TEXT,
    content_type    VARCHAR(20)     NOT NULL DEFAULT 'text',
    tool_calls      JSONB           DEFAULT '[]',
    tool_call_id    VARCHAR(128),
    token_count     INT             NOT NULL DEFAULT 0,
    metadata        JSONB           DEFAULT '{}',
    tool_events     JSONB           DEFAULT '[]',
    parent_id       BIGINT,
    create_time     TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);
CREATE INDEX idx_message_session_id ON message (session_id);
CREATE INDEX idx_message_create_time ON message (session_id, create_time);
CREATE INDEX idx_message_role ON message (session_id, role);
COMMENT ON TABLE message IS '消息表';

-- ========================================
-- 知识库表
-- ========================================
CREATE TABLE knowledge (
    id              BIGINT          NOT NULL,
    user_id         BIGINT          NOT NULL,
    name            VARCHAR(128)    NOT NULL,
    description     TEXT,
    embedding_model VARCHAR(64)     NOT NULL DEFAULT 'text-embedding-3-small',
    type            VARCHAR(32)     NOT NULL DEFAULT 'pg',
    config          JSONB           DEFAULT '{}',
    query_params    JSONB           DEFAULT '{}',
    document_count  INT             NOT NULL DEFAULT 0,
    chunk_count     INT             NOT NULL DEFAULT 0,
    total_tokens    BIGINT          NOT NULL DEFAULT 0,
    status          VARCHAR(20)     NOT NULL DEFAULT 'active',
    mindmap_data    JSONB,
    example_questions JSONB         DEFAULT '[]',
    graph_enabled   BOOLEAN         NOT NULL DEFAULT FALSE,
    node_count      INTEGER         NOT NULL DEFAULT 0,
    edge_count      INTEGER         NOT NULL DEFAULT 0,
    create_time     TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time     TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted         SMALLINT        NOT NULL DEFAULT 0,
    PRIMARY KEY (id)
);
CREATE INDEX idx_knowledge_user_id ON knowledge (user_id);
CREATE INDEX idx_knowledge_status ON knowledge (status);
CREATE INDEX idx_knowledge_type ON knowledge (type);
COMMENT ON TABLE knowledge IS '知识库表';
COMMENT ON COLUMN knowledge.type IS '知识库类型：pg / milvus';
COMMENT ON COLUMN knowledge.query_params IS '检索配置（JSONB）';
COMMENT ON COLUMN knowledge.mindmap_data IS '思维导图数据（JSON格式树状结构）';
COMMENT ON COLUMN knowledge.example_questions IS '示例问题列表（JSON数组）';
COMMENT ON COLUMN knowledge.graph_enabled IS '是否启用知识图谱';
COMMENT ON COLUMN knowledge.node_count IS '图谱节点数';
COMMENT ON COLUMN knowledge.edge_count IS '图谱边数';

-- ========================================
-- 知识库成员表（权限控制）
-- ========================================
CREATE TABLE knowledge_member (
    id              BIGINT          NOT NULL,
    knowledge_id    BIGINT          NOT NULL,
    user_id         BIGINT          NOT NULL,
    role            VARCHAR(20)     NOT NULL DEFAULT 'viewer',
    create_time     TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time     TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);
CREATE UNIQUE INDEX uk_knowledge_member ON knowledge_member (knowledge_id, user_id);
CREATE INDEX idx_knowledge_member_user_id ON knowledge_member (user_id);
COMMENT ON TABLE knowledge_member IS '知识库成员表';

-- ========================================
-- 文档表
-- ========================================
CREATE TABLE document (
    id              BIGINT          NOT NULL,
    knowledge_id    BIGINT          NOT NULL,
    user_id         BIGINT          NOT NULL,
    name            VARCHAR(256)    NOT NULL,
    file_path       VARCHAR(512),
    file_type       VARCHAR(32),
    file_size       BIGINT,
    file_hash       VARCHAR(64),
    chunk_count     INT             NOT NULL DEFAULT 0,
    token_count     BIGINT          NOT NULL DEFAULT 0,
    status          VARCHAR(20)     NOT NULL DEFAULT 'uploaded',
    error_message   TEXT,
    metadata        JSONB           DEFAULT '{}',
    markdown_path   VARCHAR(512),
    embedding_json  JSONB,
    duplicate_rate  DOUBLE PRECISION,
    duplicate_details JSONB,
    version         INTEGER         NOT NULL DEFAULT 1,
    last_edit_time  TIMESTAMP,
    create_time     TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time     TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted         SMALLINT        NOT NULL DEFAULT 0,
    PRIMARY KEY (id)
);
CREATE INDEX idx_document_knowledge_id ON document (knowledge_id);
CREATE INDEX idx_document_user_id ON document (user_id);
CREATE INDEX idx_document_status ON document (status);
CREATE INDEX idx_document_file_hash ON document (file_hash);
COMMENT ON TABLE document IS '文档表';
COMMENT ON COLUMN document.markdown_path IS 'Markdown文件存储路径';
COMMENT ON COLUMN document.embedding_json IS '入库配置（chunkStrategy/chunkSize/chunkOverlap/chunkDelimiter）';
COMMENT ON COLUMN document.duplicate_rate IS '内容重复率（与知识库已有文档的最高相似度）';
COMMENT ON COLUMN document.duplicate_details IS '重复文档详情（top3，含文档名和相似度）';
COMMENT ON COLUMN document.version IS '文档内容版本号，每次编辑递增';
COMMENT ON COLUMN document.last_edit_time IS '最后一次在线编辑时间';

-- ========================================
-- 文档分块表
-- ========================================
CREATE TABLE chunk (
    id              BIGINT          NOT NULL,
    document_id     BIGINT          NOT NULL,
    knowledge_id    BIGINT          NOT NULL,
    content         TEXT            NOT NULL,
    chunk_index     INT             NOT NULL,
    token_count     INT             NOT NULL DEFAULT 0,
    metadata        JSONB           DEFAULT '{}',
    status          VARCHAR(20)     NOT NULL DEFAULT 'chunked',
    content_tsv     tsvector,
    create_time     TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time     TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);
CREATE INDEX idx_chunk_document_id ON chunk (document_id);
CREATE INDEX idx_chunk_knowledge_id ON chunk (knowledge_id);
CREATE INDEX idx_chunk_status ON chunk (status);
CREATE INDEX idx_chunk_content_tsv ON chunk USING GIN(content_tsv);
COMMENT ON TABLE chunk IS '文档分块表';
COMMENT ON COLUMN chunk.status IS '向量化状态: chunked/vectorizing/vectorized/failed';

-- content_tsv 自动维护触发器
CREATE OR REPLACE FUNCTION update_chunk_content_tsv() RETURNS TRIGGER AS $$
BEGIN
    NEW.content_tsv := to_tsvector('simple', NEW.content);
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_chunk_content_tsv
    BEFORE INSERT OR UPDATE OF content ON chunk
    FOR EACH ROW EXECUTE FUNCTION update_chunk_content_tsv();

-- ========================================
-- 向量表
-- ========================================
CREATE TABLE embedding (
    id              BIGINT          NOT NULL,
    chunk_id        BIGINT,
    qa_pair_id      BIGINT,
    model_name      VARCHAR(64)     NOT NULL,
    dimension       INT             NOT NULL DEFAULT 1536,
    vector          vector(1536)    NOT NULL,
    create_time     TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);
CREATE UNIQUE INDEX uk_embedding_chunk_id ON embedding (chunk_id) WHERE chunk_id IS NOT NULL;
CREATE UNIQUE INDEX uk_embedding_qa_pair_id ON embedding (qa_pair_id) WHERE qa_pair_id IS NOT NULL;
CREATE INDEX idx_embedding_vector_hnsw ON embedding
    USING hnsw (vector vector_cosine_ops)
    WITH (m = 16, ef_construction = 200);
COMMENT ON TABLE embedding IS '向量表';
COMMENT ON COLUMN embedding.qa_pair_id IS '关联问答对ID，与chunk_id互斥';

-- ========================================
-- 问答对表
-- ========================================
CREATE TABLE qa_pair (
    id              BIGINT          NOT NULL,
    knowledge_id    BIGINT          NOT NULL,
    question        TEXT            NOT NULL,
    answer          TEXT            NOT NULL,
    source          VARCHAR(20)     NOT NULL DEFAULT 'manual',
    status          VARCHAR(20)     NOT NULL DEFAULT 'pending',
    token_count     INTEGER         NOT NULL DEFAULT 0,
    create_time     TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time     TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted         SMALLINT        NOT NULL DEFAULT 0,
    PRIMARY KEY (id)
);
CREATE INDEX idx_qa_pair_knowledge_id ON qa_pair (knowledge_id);
CREATE INDEX idx_qa_pair_status ON qa_pair (status);
COMMENT ON TABLE qa_pair IS '知识库问答对';
COMMENT ON COLUMN qa_pair.source IS '来源：manual-手动创建、import-批量导入、ai-AI生成';
COMMENT ON COLUMN qa_pair.status IS '状态：pending-待向量化、vectorizing-向量化中、active-生效、failed-失败';

-- ========================================
-- 图谱抽取任务表
-- ========================================
CREATE TABLE graph_extraction_task (
    id              BIGINT          NOT NULL,
    knowledge_id    BIGINT          NOT NULL,
    document_id     BIGINT,
    status          VARCHAR(20)     NOT NULL DEFAULT 'pending',
    source          VARCHAR(20)     NOT NULL DEFAULT 'auto',
    entity_count    INTEGER         NOT NULL DEFAULT 0,
    relation_count  INTEGER         NOT NULL DEFAULT 0,
    error_message   TEXT,
    create_time     TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time     TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted         SMALLINT        NOT NULL DEFAULT 0,
    PRIMARY KEY (id)
);
CREATE INDEX idx_graph_task_knowledge_id ON graph_extraction_task (knowledge_id);
CREATE INDEX idx_graph_task_status ON graph_extraction_task (status);
COMMENT ON TABLE graph_extraction_task IS '图谱抽取任务';
COMMENT ON COLUMN graph_extraction_task.source IS '来源：auto-自动抽取、import-手动导入';
COMMENT ON COLUMN graph_extraction_task.status IS '状态：pending-待处理、running-执行中、completed-已完成、failed-失败';

-- ========================================
-- 知识图表（知识库级别）
-- ========================================
CREATE TABLE knowledge_graph (
    id              BIGINT          NOT NULL,
    knowledge_id    BIGINT          NOT NULL,
    status          VARCHAR(20)     NOT NULL DEFAULT 'pending',
    node_count      INTEGER         NOT NULL DEFAULT 0,
    edge_count      INTEGER         NOT NULL DEFAULT 0,
    task_id         BIGINT,
    error_message   TEXT,
    create_time     TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time     TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted         SMALLINT        NOT NULL DEFAULT 0,
    PRIMARY KEY (id)
);
CREATE UNIQUE INDEX uk_knowledge_graph_knowledge_id ON knowledge_graph (knowledge_id) WHERE deleted = 0;
COMMENT ON TABLE knowledge_graph IS '知识图谱（知识库级别）';
COMMENT ON COLUMN knowledge_graph.status IS '状态：pending-待处理、running-执行中、completed-已完成、failed-失败';
COMMENT ON COLUMN knowledge_graph.task_id IS '当前正在运行的异步任务ID';

-- ========================================
-- 图谱文档关联表
-- ========================================
CREATE TABLE graph_document (
    id              BIGINT          NOT NULL,
    graph_id        BIGINT          NOT NULL,
    document_id     BIGINT          NOT NULL,
    status          VARCHAR(20)     NOT NULL DEFAULT 'pending',
    entity_count    INTEGER         NOT NULL DEFAULT 0,
    relation_count  INTEGER         NOT NULL DEFAULT 0,
    error_message   TEXT,
    create_time     TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time     TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted         SMALLINT        NOT NULL DEFAULT 0,
    PRIMARY KEY (id)
);
CREATE INDEX idx_graph_document_graph_id ON graph_document (graph_id);
CREATE UNIQUE INDEX uk_graph_document_graph_doc ON graph_document (graph_id, document_id) WHERE deleted = 0;
COMMENT ON TABLE graph_document IS '图谱文档关联（记录每个文档的图谱抽取状态）';
COMMENT ON COLUMN graph_document.status IS '状态：pending-待处理、running-执行中、completed-已完成、failed-失败';

-- ========================================
-- 文档版本历史表
-- ========================================
CREATE TABLE document_version (
    id              BIGINT          NOT NULL,
    document_id     BIGINT          NOT NULL,
    version         INTEGER         NOT NULL,
    content_hash    VARCHAR(64),
    storage_path    VARCHAR(512)    NOT NULL,
    created_by      BIGINT,
    create_time     TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);
CREATE INDEX idx_doc_version_doc ON document_version (document_id, version DESC);
COMMENT ON TABLE document_version IS '文档版本历史';

-- ========================================
-- Tool 表
-- ========================================
CREATE TABLE tool (
    id              BIGINT          NOT NULL,
    user_id         BIGINT,
    name            VARCHAR(64)     NOT NULL,
    display_name    VARCHAR(128),
    description     TEXT,
    tool_type       VARCHAR(32)     NOT NULL DEFAULT 'builtin',
    input_schema    JSONB           NOT NULL DEFAULT '{}',
    output_schema   JSONB           DEFAULT '{}',
    config          JSONB           DEFAULT '{}',
    endpoint_url    VARCHAR(512),
    auth_type       VARCHAR(32),
    auth_config     JSONB           DEFAULT '{}',
    status          VARCHAR(20)     NOT NULL DEFAULT 'active',
    tags            JSONB           NOT NULL DEFAULT '[]',
    icon            VARCHAR(64),
    create_time     TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time     TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted         SMALLINT        NOT NULL DEFAULT 0,
    PRIMARY KEY (id)
);
CREATE UNIQUE INDEX uk_tool_name ON tool (name) WHERE deleted = 0;
CREATE INDEX idx_tool_type ON tool (tool_type);
CREATE INDEX idx_tool_status ON tool (status);
CREATE INDEX idx_tool_tags ON tool USING GIN (tags);
COMMENT ON TABLE tool IS 'Tool表';
COMMENT ON COLUMN tool.tags IS '工具标签（JSONB数组）';
COMMENT ON COLUMN tool.icon IS '图标标识（Ant Design 图标组件名）';

-- ========================================
-- Skill 表
-- ========================================
CREATE TABLE skill (
    id              BIGINT          NOT NULL,
    agent_id        BIGINT,
    tool_id         BIGINT,
    name            VARCHAR(128)    NOT NULL,
    description     TEXT,
    prompt_template TEXT,
    config          JSONB           DEFAULT '{}',
    sort_order      INT             NOT NULL DEFAULT 0,
    status          VARCHAR(20)     NOT NULL DEFAULT 'active',
    slug            VARCHAR(128),
    display_name    VARCHAR(128),
    tool_ids        JSONB           NOT NULL DEFAULT '[]',
    mcp_server_ids  JSONB           NOT NULL DEFAULT '[]',
    model_id        BIGINT,
    scope           VARCHAR(20)     NOT NULL DEFAULT 'global',
    is_builtin      SMALLINT        NOT NULL DEFAULT 0,
    content_hash    VARCHAR(128),
    object_prefix   VARCHAR(256),
    version         VARCHAR(64)     DEFAULT '1.0.0',
    skill_dependencies JSONB        DEFAULT '[]',
    source_type     VARCHAR(20)     DEFAULT 'builtin',
    icon            VARCHAR(64),
    user_id         BIGINT,
    create_time     TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time     TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted         SMALLINT        NOT NULL DEFAULT 0,
    PRIMARY KEY (id)
);
CREATE INDEX idx_skill_agent_id ON skill (agent_id);
CREATE INDEX idx_skill_tool_id ON skill (tool_id);
CREATE UNIQUE INDEX uk_skill_slug ON skill (slug) WHERE slug IS NOT NULL AND deleted = 0;
CREATE INDEX idx_skill_is_builtin ON skill (is_builtin);
CREATE INDEX idx_skill_scope ON skill (scope);
CREATE INDEX idx_skill_source_type ON skill (source_type);
COMMENT ON TABLE skill IS 'Skill表';
COMMENT ON COLUMN skill.slug IS '全局唯一标识（英文-小写-短横线），全局 Skill 必填';
COMMENT ON COLUMN skill.display_name IS '显示名称（中文）';
COMMENT ON COLUMN skill.tool_ids IS '依赖的 Tool ID 列表（JSON 数组，字符串形式）';
COMMENT ON COLUMN skill.mcp_server_ids IS '依赖的 MCP Server ID 列表（JSON 数组，字符串形式）';
COMMENT ON COLUMN skill.model_id IS '可选的模型覆盖（保留字段，当前未启用）';
COMMENT ON COLUMN skill.scope IS '作用域：global=全局可复用；agent=旧的按 Agent 私有（兼容）';
COMMENT ON COLUMN skill.is_builtin IS '是否内置：1=是（不可编辑/删除），0=否';
COMMENT ON COLUMN skill.content_hash IS '内置 Skill 内容 hash，用于检测代码版本变化';
COMMENT ON COLUMN skill.object_prefix IS 'MinIO 路径前缀，如 skills/{slug}/';
COMMENT ON COLUMN skill.version IS '语义版本号';
COMMENT ON COLUMN skill.skill_dependencies IS '依赖其他 Skill 的 slug 列表';
COMMENT ON COLUMN skill.source_type IS '来源类型: builtin/upload/remote';
COMMENT ON COLUMN skill.icon IS '图标标识（Ant Design 图标组件名）';
COMMENT ON COLUMN skill.user_id IS '创建者ID（global skill 可为空）';

-- ========================================
-- 工具调用记录表
-- ========================================
CREATE TABLE tool_calls (
    id              BIGINT          NOT NULL,
    message_id      BIGINT,
    tool_name       VARCHAR(100)    NOT NULL,
    tool_input      JSONB,
    tool_output     TEXT,
    status          VARCHAR(20)     NOT NULL DEFAULT 'pending',
    error_message   TEXT,
    created_at      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);
CREATE INDEX ix_tool_calls_message_id ON tool_calls (message_id);
COMMENT ON TABLE tool_calls IS '工具调用记录表';
COMMENT ON COLUMN tool_calls.message_id IS '关联消息ID';
COMMENT ON COLUMN tool_calls.tool_name IS '工具名称';
COMMENT ON COLUMN tool_calls.tool_input IS '工具输入参数';
COMMENT ON COLUMN tool_calls.tool_output IS '工具执行结果';
COMMENT ON COLUMN tool_calls.status IS '状态: pending/success/error';
COMMENT ON COLUMN tool_calls.error_message IS '错误信息';

-- ========================================
-- MCP Server 表
-- ========================================
CREATE TABLE mcp_server (
    id              BIGINT          NOT NULL,
    name            VARCHAR(128)    NOT NULL,
    description     VARCHAR(512),
    install_type    VARCHAR(20)     NOT NULL,
    deploy_config   JSONB,
    detail_config   JSONB,
    host            VARCHAR(256),
    status          VARCHAR(20)     NOT NULL DEFAULT 'active',
    user_id         BIGINT,
    transport       VARCHAR(20)     NOT NULL DEFAULT 'sse',
    headers         JSONB,
    disabled_tools  JSONB,
    icon            VARCHAR(64),
    create_time     TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time     TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted         SMALLINT        NOT NULL DEFAULT 0,
    PRIMARY KEY (id)
);
CREATE INDEX idx_mcp_server_user_id ON mcp_server (user_id);
COMMENT ON TABLE mcp_server IS 'MCP Server表';
COMMENT ON COLUMN mcp_server.transport IS '传输类型: sse, stdio, streamable_http';
COMMENT ON COLUMN mcp_server.headers IS 'HTTP请求头(JSONB)，用于SSE/Streamable HTTP认证';
COMMENT ON COLUMN mcp_server.disabled_tools IS '禁用的工具名列表(JSONB数组)';
COMMENT ON COLUMN mcp_server.icon IS '图标标识（Ant Design 图标组件名）';

-- ========================================
-- Prompt 定义表
-- ========================================
CREATE TABLE prompt (
    id              BIGINT          NOT NULL,
    prompt_key      VARCHAR(128)    NOT NULL,
    description     VARCHAR(512),
    latest_version  VARCHAR(32),
    tags            VARCHAR(512),
    user_id         BIGINT,
    create_time     TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time     TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted         SMALLINT        NOT NULL DEFAULT 0,
    PRIMARY KEY (id)
);
CREATE UNIQUE INDEX uk_prompt_key ON prompt (prompt_key) WHERE deleted = 0;
CREATE INDEX idx_prompt_user_id ON prompt (user_id);
COMMENT ON TABLE prompt IS 'Prompt定义表';

-- ========================================
-- Prompt 版本表
-- ========================================
CREATE TABLE prompt_version (
    id              BIGINT          NOT NULL,
    prompt_key      VARCHAR(128)    NOT NULL,
    version         VARCHAR(32)     NOT NULL,
    version_desc    VARCHAR(512),
    template        TEXT            NOT NULL,
    variables       JSONB           DEFAULT '{}',
    model_config    JSONB           DEFAULT '{}',
    tool_config     JSONB           DEFAULT '{}',
    status          VARCHAR(20)     NOT NULL DEFAULT 'pre',
    user_id         BIGINT,
    create_time     TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time     TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted         SMALLINT        NOT NULL DEFAULT 0,
    PRIMARY KEY (id)
);
CREATE UNIQUE INDEX uk_prompt_version ON prompt_version (prompt_key, version) WHERE deleted = 0;
CREATE INDEX idx_prompt_version_key ON prompt_version (prompt_key);
COMMENT ON TABLE prompt_version IS 'Prompt版本表';
COMMENT ON COLUMN prompt_version.tool_config IS '工具配置（JSON格式，存储Prompt关联的工具列表）';

-- ========================================
-- Prompt 构建模板表
-- ========================================
CREATE TABLE prompt_build_template (
    id                      BIGINT          NOT NULL,
    prompt_template_key     VARCHAR(128)    NOT NULL,
    tags                    VARCHAR(256),
    template_desc           VARCHAR(512),
    template                TEXT            NOT NULL,
    variables               VARCHAR(1024),
    model_config            JSONB           DEFAULT '{}',
    tool_config             JSONB           DEFAULT '{}',
    create_time             TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time             TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted                 SMALLINT        NOT NULL DEFAULT 0,
    PRIMARY KEY (id)
);
CREATE UNIQUE INDEX uk_prompt_build_template_key ON prompt_build_template (prompt_template_key) WHERE deleted = 0;
COMMENT ON TABLE prompt_build_template IS 'Prompt构建模板表';
COMMENT ON COLUMN prompt_build_template.tool_config IS '工具配置（JSON格式）';

-- ========================================
-- 任务队列表
-- ========================================
CREATE TABLE task (
    id               BIGINT        NOT NULL,
    name             VARCHAR(256)  NOT NULL,
    type             VARCHAR(50)   NOT NULL,
    status           VARCHAR(20)   NOT NULL DEFAULT 'pending',
    progress         SMALLINT      NOT NULL DEFAULT 0,
    message          VARCHAR(512),
    payload          TEXT,
    result           TEXT,
    error            TEXT,
    cancel_requested SMALLINT      NOT NULL DEFAULT 0,
    user_id          BIGINT        NOT NULL,
    ref_id           BIGINT,
    create_time      TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time      TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    started_at       TIMESTAMP,
    completed_at     TIMESTAMP,
    deleted          SMALLINT      NOT NULL DEFAULT 0,
    PRIMARY KEY (id)
);
CREATE INDEX idx_task_user_id ON task (user_id);
CREATE INDEX idx_task_status ON task (status);
CREATE INDEX idx_task_type ON task (type);
COMMENT ON TABLE task IS '任务队列表';

-- ========================================
-- LLM 调用链追踪表
-- ========================================
CREATE TABLE llm_trace (
    id              BIGINT          NOT NULL,
    request_id      VARCHAR(64)     NOT NULL,
    session_id      BIGINT,
    user_id         BIGINT,
    agent_id        BIGINT,
    agent_name      VARCHAR(128),
    model           VARCHAR(128),
    status          VARCHAR(20)     NOT NULL DEFAULT 'running',
    input_tokens    INT             NOT NULL DEFAULT 0,
    output_tokens   INT             NOT NULL DEFAULT 0,
    total_tokens    INT             NOT NULL DEFAULT 0,
    tool_call_count INT             NOT NULL DEFAULT 0,
    total_duration_ms BIGINT        NOT NULL DEFAULT 0,
    spans           JSONB           DEFAULT '[]',
    error_message   TEXT,
    reply_content   TEXT,
    display_content TEXT,
    trace_source    VARCHAR(32),
    create_time     TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);
CREATE INDEX idx_llm_trace_request_id ON llm_trace (request_id);
CREATE INDEX idx_llm_trace_session_id ON llm_trace (session_id);
CREATE INDEX idx_llm_trace_user_id ON llm_trace (user_id);
CREATE INDEX idx_llm_trace_create_time ON llm_trace (create_time);
CREATE INDEX idx_llm_trace_status ON llm_trace (status);
CREATE INDEX idx_llm_trace_trace_source ON llm_trace (trace_source);
COMMENT ON TABLE llm_trace IS 'LLM调用链追踪表';
COMMENT ON COLUMN llm_trace.request_id IS '请求ID（唯一标识一次AI对话）';
COMMENT ON COLUMN llm_trace.session_id IS '会话ID';
COMMENT ON COLUMN llm_trace.user_id IS '用户ID';
COMMENT ON COLUMN llm_trace.agent_id IS 'AgentID';
COMMENT ON COLUMN llm_trace.agent_name IS 'Agent名称';
COMMENT ON COLUMN llm_trace.model IS '模型标识';
COMMENT ON COLUMN llm_trace.status IS '状态: running/completed/failed';
COMMENT ON COLUMN llm_trace.input_tokens IS '输入Token数';
COMMENT ON COLUMN llm_trace.output_tokens IS '输出Token数';
COMMENT ON COLUMN llm_trace.total_tokens IS '总Token数';
COMMENT ON COLUMN llm_trace.tool_call_count IS '工具调用次数';
COMMENT ON COLUMN llm_trace.total_duration_ms IS '总耗时（毫秒）';
COMMENT ON COLUMN llm_trace.spans IS '调用链Span列表（JSONB）';
COMMENT ON COLUMN llm_trace.error_message IS '错误信息';
COMMENT ON COLUMN llm_trace.reply_content IS 'AI完整回复内容（模型原始输出，含深度思考标签，不做删改）';
COMMENT ON COLUMN llm_trace.display_content IS '最终展示内容（用户对话页可见正文，已剥离思考标签）';
COMMENT ON COLUMN llm_trace.trace_source IS '来源：chat=用户对话；辅助 LLM 调用不写入';

-- 性能索引
CREATE INDEX idx_llm_trace_source_time ON llm_trace (trace_source, create_time DESC);
CREATE INDEX idx_llm_trace_agent_source ON llm_trace (agent_id, trace_source);
CREATE INDEX idx_tool_calls_created_at ON tool_calls (created_at DESC);
CREATE INDEX idx_chat_session_user_agent ON chat_session (user_id, agent_id);

-- ========================================
-- 系统配置表
-- ========================================
CREATE TABLE system_config (
    config_key   VARCHAR(64)    NOT NULL,
    config_value TEXT,
    description  VARCHAR(255),
    create_time  TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time  TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (config_key)
);
COMMENT ON TABLE system_config IS '系统配置表';
COMMENT ON COLUMN system_config.config_key IS '配置键，如 default_ai_provider';
COMMENT ON COLUMN system_config.config_value IS '配置值，JSON格式';
COMMENT ON COLUMN system_config.description IS '配置描述';

-- ========================================
-- 评测集表
-- ========================================
CREATE TABLE eval_dataset (
    id              BIGINT          NOT NULL,
    name            VARCHAR(128)    NOT NULL,
    description     VARCHAR(512),
    columns_config  JSONB           DEFAULT '[]',
    user_id         BIGINT,
    create_time     TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time     TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted         SMALLINT        NOT NULL DEFAULT 0,
    PRIMARY KEY (id)
);
CREATE INDEX idx_eval_dataset_user_id ON eval_dataset (user_id);
COMMENT ON TABLE eval_dataset IS '评测集表';

-- ========================================
-- 评测集版本表
-- ========================================
CREATE TABLE eval_dataset_version (
    id              BIGINT          NOT NULL,
    dataset_id      BIGINT          NOT NULL,
    version         VARCHAR(32)     NOT NULL,
    data_count      INT             NOT NULL DEFAULT 0,
    status          VARCHAR(20)     NOT NULL DEFAULT 'draft',
    dataset_items   JSONB           DEFAULT '[]',
    create_time     TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time     TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted         SMALLINT        NOT NULL DEFAULT 0,
    PRIMARY KEY (id)
);
CREATE UNIQUE INDEX uk_eval_dataset_version ON eval_dataset_version (dataset_id, version) WHERE deleted = 0;
CREATE INDEX idx_eval_dataset_version_dataset_id ON eval_dataset_version (dataset_id);
COMMENT ON TABLE eval_dataset_version IS '评测集版本表';

-- ========================================
-- 评测数据项表
-- ========================================
CREATE TABLE eval_dataset_item (
    id              BIGINT          NOT NULL,
    dataset_id      BIGINT          NOT NULL,
    data_content    JSONB           DEFAULT '{}',
    create_time     TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time     TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted         SMALLINT        NOT NULL DEFAULT 0,
    PRIMARY KEY (id)
);
CREATE INDEX idx_eval_dataset_item_dataset_id ON eval_dataset_item (dataset_id);
COMMENT ON TABLE eval_dataset_item IS '评测数据项表';

-- ========================================
-- 评估器表
-- ========================================
CREATE TABLE eval_evaluator (
    id              BIGINT          NOT NULL,
    name            VARCHAR(128)    NOT NULL,
    description     VARCHAR(512),
    tags            VARCHAR(200),
    user_id         BIGINT,
    create_time     TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time     TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted         SMALLINT        NOT NULL DEFAULT 0,
    PRIMARY KEY (id)
);
CREATE INDEX idx_eval_evaluator_user_id ON eval_evaluator (user_id);
COMMENT ON TABLE eval_evaluator IS '评估器表';
COMMENT ON COLUMN eval_evaluator.tags IS '标签，逗号分隔';

-- ========================================
-- 评估器版本表
-- ========================================
CREATE TABLE eval_evaluator_version (
    id              BIGINT          NOT NULL,
    evaluator_id    BIGINT          NOT NULL,
    version         VARCHAR(32)     NOT NULL,
    model_config    JSONB           DEFAULT '{}',
    prompt          TEXT,
    variables       JSONB           DEFAULT '{}',
    status          VARCHAR(20)     NOT NULL DEFAULT 'draft',
    create_time     TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time     TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted         SMALLINT        NOT NULL DEFAULT 0,
    PRIMARY KEY (id)
);
CREATE UNIQUE INDEX uk_eval_evaluator_version ON eval_evaluator_version (evaluator_id, version) WHERE deleted = 0;
CREATE INDEX idx_eval_evaluator_version_evaluator_id ON eval_evaluator_version (evaluator_id);
COMMENT ON TABLE eval_evaluator_version IS '评估器版本表';

-- ========================================
-- 评估器模板表
-- ========================================
CREATE TABLE eval_evaluator_template (
    id                      BIGINT          NOT NULL,
    evaluator_template_key  VARCHAR(128)    NOT NULL,
    template_desc           VARCHAR(512),
    template                TEXT            NOT NULL,
    variables               VARCHAR(1024),
    model_config            JSONB           DEFAULT '{}',
    create_time             TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time             TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted                 SMALLINT        NOT NULL DEFAULT 0,
    PRIMARY KEY (id)
);
CREATE UNIQUE INDEX uk_eval_evaluator_template_key ON eval_evaluator_template (evaluator_template_key) WHERE deleted = 0;
COMMENT ON TABLE eval_evaluator_template IS '评估器模板表';

-- ========================================
-- 实验表
-- ========================================
CREATE TABLE eval_experiment (
    id                          BIGINT          NOT NULL,
    name                        VARCHAR(128)    NOT NULL,
    description                 VARCHAR(512),
    dataset_id                  BIGINT,
    dataset_version_id          BIGINT,
    dataset_version             VARCHAR(32),
    evaluation_object_config    JSONB           DEFAULT '{}',
    evaluator_config            JSONB           DEFAULT '[]',
    status                      VARCHAR(20)     NOT NULL DEFAULT 'draft',
    progress                    INT             NOT NULL DEFAULT 0,
    complete_time               TIMESTAMP,
    user_id                     BIGINT,
    task_id                     BIGINT,
    create_time                 TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time                 TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted                     SMALLINT        NOT NULL DEFAULT 0,
    PRIMARY KEY (id)
);
CREATE INDEX idx_eval_experiment_user_id ON eval_experiment (user_id);
CREATE INDEX idx_eval_experiment_status ON eval_experiment (status);
COMMENT ON TABLE eval_experiment IS '评测实验表';

-- ========================================
-- 实验结果表
-- ========================================
CREATE TABLE eval_experiment_result (
    id                      BIGINT          NOT NULL,
    experiment_id           BIGINT          NOT NULL,
    input                   TEXT,
    actual_output           TEXT,
    reference_output        TEXT,
    score                   DECIMAL(3,2),
    reason                  TEXT,
    evaluator_version_id    BIGINT,
    evaluator_name          VARCHAR(128),
    evaluation_time         TIMESTAMP,
    create_time             TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time             TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted                 SMALLINT        NOT NULL DEFAULT 0,
    PRIMARY KEY (id)
);
CREATE INDEX idx_eval_experiment_result_experiment_id ON eval_experiment_result (experiment_id);
CREATE INDEX idx_eval_experiment_result_evaluator ON eval_experiment_result (evaluator_version_id);
COMMENT ON TABLE eval_experiment_result IS '实验结果表';

-- ========================================
-- RAG 评估基准表
-- ========================================
CREATE TABLE eval_rag_benchmark (
    id              BIGINT        NOT NULL,
    knowledge_id    BIGINT        NOT NULL,
    name            VARCHAR(128)  NOT NULL,
    description     VARCHAR(512),
    question_count  INT           NOT NULL DEFAULT 0,
    status          VARCHAR(20)   NOT NULL DEFAULT 'ready',
    create_time     TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time     TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted         SMALLINT      NOT NULL DEFAULT 0,
    PRIMARY KEY (id)
);
CREATE INDEX idx_eval_rag_benchmark_knowledge_id ON eval_rag_benchmark (knowledge_id);
COMMENT ON TABLE eval_rag_benchmark IS 'RAG 评估基准表';
COMMENT ON COLUMN eval_rag_benchmark.status IS '状态：generating-生成中, ready-就绪';

-- ========================================
-- RAG 评估基准题目表
-- ========================================
CREATE TABLE eval_rag_benchmark_item (
    id              BIGINT        NOT NULL,
    benchmark_id    BIGINT        NOT NULL,
    query           VARCHAR(2000) NOT NULL,
    gold_chunk_ids  VARCHAR(2000),
    gold_answer     TEXT,
    sort_order      INT           NOT NULL DEFAULT 0,
    PRIMARY KEY (id)
);
CREATE INDEX idx_eval_rag_benchmark_item_benchmark_id ON eval_rag_benchmark_item (benchmark_id);
COMMENT ON TABLE eval_rag_benchmark_item IS 'RAG 评估基准题目表';

-- ========================================
-- RAG 评估结果表
-- ========================================
CREATE TABLE eval_rag_result (
    id              BIGINT        NOT NULL,
    knowledge_id    BIGINT        NOT NULL,
    benchmark_id    BIGINT        NOT NULL,
    benchmark_name  VARCHAR(128),
    status          VARCHAR(20)   NOT NULL DEFAULT 'RUNNING',
    overall_score   DOUBLE PRECISION,
    retrieval_json  TEXT,
    answer_json     TEXT,
    config_json     TEXT,
    duration_ms     BIGINT,
    analysis        TEXT,
    error           TEXT,
    create_time     TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time     TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted         SMALLINT      NOT NULL DEFAULT 0,
    PRIMARY KEY (id)
);
CREATE INDEX idx_eval_rag_result_knowledge_id ON eval_rag_result (knowledge_id);
COMMENT ON TABLE eval_rag_result IS 'RAG 评估结果表';
COMMENT ON COLUMN eval_rag_result.analysis IS 'AI评估分析报告';

-- ========================================
-- RAG 评估结果详情表
-- ========================================
CREATE TABLE eval_rag_result_detail (
    id                  BIGINT        NOT NULL,
    result_id           BIGINT        NOT NULL,
    query               VARCHAR(2000) NOT NULL,
    gold_chunk_ids      VARCHAR(2000),
    gold_answer         TEXT,
    generated_answer    TEXT,
    retrieved_chunk_ids VARCHAR(2000),
    retrieval_scores    TEXT,
    answer_score        DOUBLE PRECISION,
    answer_reasoning    TEXT,
    sort_order          INT           NOT NULL DEFAULT 0,
    PRIMARY KEY (id)
);
CREATE INDEX idx_eval_rag_result_detail_result_id ON eval_rag_result_detail (result_id);
COMMENT ON COLUMN eval_rag_result_detail.answer_reasoning IS 'RAG 评估结果详情表';

-- ========================================
-- 工作流编排页测试运行记录表
-- ========================================
CREATE TABLE workflow_test_run (
    id              BIGINT          NOT NULL,
    run_id          VARCHAR(64)     NOT NULL,
    agent_id        BIGINT          NOT NULL,
    user_id         BIGINT          NOT NULL,
    test_mode       VARCHAR(20)     NOT NULL DEFAULT 'generation',
    used_draft      SMALLINT        NOT NULL DEFAULT 1,
    status          VARCHAR(20)     NOT NULL DEFAULT 'running',
    user_input      TEXT,
    output          TEXT,
    node_events     JSONB           NOT NULL DEFAULT '[]',
    variables       JSONB,
    workflow_graph  JSONB,
    error_info      TEXT,
    duration_ms     BIGINT,
    start_time      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    end_time        TIMESTAMP,
    create_time     TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time     TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted         SMALLINT        NOT NULL DEFAULT 0,
    PRIMARY KEY (id)
);
CREATE UNIQUE INDEX uk_workflow_test_run_run_id ON workflow_test_run (run_id);
CREATE INDEX idx_workflow_test_run_agent_time ON workflow_test_run (agent_id, start_time DESC);
COMMENT ON TABLE workflow_test_run IS '工作流编排页测试运行记录';

-- ========================================
-- 用户长期记忆表
-- ========================================
CREATE TABLE user_memory (
    id                  BIGINT          NOT NULL,
    user_id             BIGINT          NOT NULL,
    api_key_id          BIGINT,
    external_user_id    VARCHAR(128),
    agent_id            BIGINT,
    session_id          BIGINT,
    memory_type         VARCHAR(32)     NOT NULL,
    content             TEXT            NOT NULL,
    keywords            JSONB           NOT NULL DEFAULT '[]'::jsonb,
    source_message_id   BIGINT,
    confidence          NUMERIC(5,4)    NOT NULL DEFAULT 1.0000,
    status              VARCHAR(32)     NOT NULL DEFAULT 'active',
    embedding_vector    vector(1536),
    last_used_at        TIMESTAMP,
    create_time         TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time         TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted             SMALLINT        NOT NULL DEFAULT 0,
    PRIMARY KEY (id)
);
CREATE INDEX idx_user_memory_user_status ON user_memory (user_id, status);
CREATE INDEX idx_user_memory_api_external ON user_memory (api_key_id, external_user_id, status)
    WHERE api_key_id IS NOT NULL AND external_user_id IS NOT NULL;
CREATE INDEX idx_user_memory_agent ON user_memory (agent_id);
CREATE INDEX idx_user_memory_type ON user_memory (memory_type);
CREATE INDEX idx_user_memory_vector_hnsw ON user_memory
    USING hnsw (embedding_vector vector_cosine_ops)
    WHERE embedding_vector IS NOT NULL AND deleted = 0;
COMMENT ON TABLE user_memory IS '用户长期记忆表';
COMMENT ON COLUMN user_memory.memory_type IS '记忆类型：preference/profile/project_fact/instruction';
COMMENT ON COLUMN user_memory.status IS '状态：active/disabled/archived';
COMMENT ON COLUMN user_memory.embedding_vector IS '记忆语义向量，用于长期记忆语义检索';
COMMENT ON COLUMN user_memory.api_key_id IS '企业 API Key ID（开放 API 外部用户记忆）';
COMMENT ON COLUMN user_memory.external_user_id IS '上层业务终端用户标识';

-- ========================================
-- SubAgent 委派批次表
-- ========================================
CREATE TABLE subagent_task_batch (
    id                  BIGINT          NOT NULL,
    batch_id            VARCHAR(80)     NOT NULL,
    parent_request_id   VARCHAR(100),
    parent_thread_id    VARCHAR(100),
    parent_session_id   BIGINT,
    mode                VARCHAR(20)     NOT NULL,
    aggregation         VARCHAR(32)     NOT NULL DEFAULT 'return_all',
    status              VARCHAR(20)     NOT NULL DEFAULT 'pending',
    total_count         INTEGER         NOT NULL DEFAULT 0,
    completed_count     INTEGER         NOT NULL DEFAULT 0,
    failed_count        INTEGER         NOT NULL DEFAULT 0,
    cancelled_count     INTEGER         NOT NULL DEFAULT 0,
    cancel_requested    SMALLINT        NOT NULL DEFAULT 0,
    create_time         TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time         TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);
CREATE UNIQUE INDEX uk_subagent_task_batch_batch_id ON subagent_task_batch(batch_id);
CREATE INDEX idx_subagent_task_batch_parent_request ON subagent_task_batch(parent_request_id);
CREATE INDEX idx_subagent_task_batch_status ON subagent_task_batch(status);
COMMENT ON TABLE subagent_task_batch IS 'SubAgent 委派批次表';
COMMENT ON COLUMN subagent_task_batch.batch_id IS '批次ID';
COMMENT ON COLUMN subagent_task_batch.status IS '批次状态：pending/running/completed/failed/cancelled';
COMMENT ON COLUMN subagent_task_batch.cancel_requested IS '是否请求取消：0否 1是';

-- ========================================
-- SubAgent 任务运行事件表
-- ========================================
CREATE TABLE subagent_task_event (
    id          BIGINT          NOT NULL,
    task_id     VARCHAR(100)    NOT NULL,
    batch_id    VARCHAR(80),
    event_type  VARCHAR(64)     NOT NULL,
    payload     TEXT            NOT NULL DEFAULT '{}',
    create_time TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);
CREATE INDEX idx_subagent_task_event_task_cursor ON subagent_task_event(task_id, id);
CREATE INDEX idx_subagent_task_event_batch_id ON subagent_task_event(batch_id);
COMMENT ON TABLE subagent_task_event IS 'SubAgent任务运行事件表，支持游标增量读取';

-- ============================================================
-- 预制数据
-- ============================================================

-- 内置默认Agent（id=1）
INSERT INTO agent (id, user_id, name, description, agent_type, system_prompt, welcome_message, status, is_default, version, create_time, update_time, deleted)
VALUES (
    1, 1, '智元助手', '默认AI助手', 'chat',
    '你是智元智能助手，请用中文回答用户问题。回答应简洁准确，遇到不确定的信息请如实告知。',
    '## 你好，我是智元
有什么可以帮你的？',
    'published', FALSE, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0
) ON CONFLICT (id) DO NOTHING;

-- 系统配置
INSERT INTO system_config (config_key, config_value, description) VALUES
('default_ai_provider', '{"providerId": null, "modelId": null}', '默认AI模型配置（生成提示词、推荐问题等功能使用）'),
('default_chat_model', '{"providerId": null, "modelId": null}', '默认对话模型配置'),
('default_embedding_model', '{"providerId": null, "modelId": null}', '默认向量模型配置（知识库文档嵌入等场景使用）'),
('default_tts_model', '{"providerId": null, "modelId": null}', '默认TTS模型配置（语音合成等场景使用）'),
('default_rerank_model', '{"providerId": null, "modelId": null}', '默认重排模型配置（知识库检索精排等场景使用）'),
('long_memory_config', '{"enabled":true,"autoExtract":true,"injectLimit":6,"scope":"user"}', '企业长期记忆默认策略')
ON CONFLICT (config_key) DO NOTHING;

-- Landing 页面配置
INSERT INTO system_config (config_key, config_value, description) VALUES (
  'landing_config',
  '{
    "title": "智元",
    "subtitle": "AI Native 智能体平台",
    "subtitles": [
      "AI Native 智能体平台",
      "一站式 RAG 知识库引擎",
      "可视化 Workflow 编排",
      "MCP 协议生态集成",
      "全链路评测与可观测"
    ],
    "description": "构建智能体、知识库、工作流与工具集成的统一平台。从 Prompt 工程到 RAG 检索增强，从 Workflow 编排到 MCP 工具生态，智元为 AI 应用开发提供全栈能力支撑。",
    "features": [
      {"icon": "Agent", "title": "智能体", "desc": "多模型驱动的自主推理 Agent，支持工具调用、记忆管理和多轮对话"},
      {"icon": "SubAgent", "title": "子智能体", "desc": "多 Agent 协作编排，支持任务分解与子智能体调度"},
      {"icon": "Knowledge", "title": "知识库", "desc": "向量检索 + 图谱融合的 RAG 引擎，精准召回知识增强生成"},
      {"icon": "Workflow", "title": "工作流", "desc": "可视化 DAG 编排，支持条件分支、并行执行和人工审批节点"},
      {"icon": "Mcp", "title": "MCP 协议", "desc": "标准 Model Context Protocol 集成，即插即用外部工具生态"},
      {"icon": "Tool", "title": "工具系统", "desc": "HTTP/函数/脚本多类型工具，统一 Schema 定义与安全沙箱执行"},
      {"icon": "Skill", "title": "技能市场", "desc": "可复用的 Prompt + Tool 组合，一键发布到技能市场共享"},
      {"icon": "Prompt", "title": "Prompt 工程", "desc": "模板化提示词管理，支持版本控制与 A/B 测试优化"},
      {"icon": "Eval", "title": "评测中心", "desc": "数据集管理、自动评估、实验对比，量化 Agent 质量持续优化"},
      {"icon": "Observability", "title": "可观测性", "desc": "全链路 Trace 追踪、Token 消耗统计、工具调用日志实时监控"}
    ],
    "copyright": "© 2026 智元. All Rights Reserved."
  }',
  'Landing 页面配置（标题、描述、功能列表等）'
)
ON CONFLICT (config_key) DO NOTHING;

-- 评估器模板（3个）
INSERT INTO eval_evaluator_template (id, evaluator_template_key, template_desc, template, variables, model_config) VALUES
(10001, 'text_similarity', '文本相似度评估', '请评估以下两个文本的相似度，分数范围为0-1，保留两位小数。

文本1：{{reference_output}}

文本2：{{actual_output}}

相似度分数：', 'reference_output,actual_output', '{"temperature": 0.1}'),
(10002, 'code_quality', '代码质量评估', '请评估以下代码的质量，从可读性、效率和最佳实践三个方面进行分析，并给出0-1的总分，保留两位小数。

代码：
{{code}}

评估报告：', 'code', '{"temperature": 0.2}'),
(10003, 'sentiment_analysis', '情感分析评估', '请分析以下文本的情感倾向，输出-1到1之间的情感分数，其中-1表示非常负面，0表示中性，1表示非常正面，保留两位小数。

文本：{{text}}

情感分数：', 'text', '{"temperature": 0.1}');

-- Prompt 构建模板（16个）
INSERT INTO prompt_build_template (id, prompt_template_key, tags, template_desc, template, variables, model_config, tool_config) VALUES
(10001, 'general_assistant', '通用,助手', '通用AI助手模板', '你是一个专业的AI助手。请根据用户的问题提供准确、有帮助的回答。

角色：{{role}}
任务：{{task}}

用户输入：{{user_input}}', 'role,task,user_input', '{"temperature": 0.7}', '{}'),
(10002, 'code_reviewer', '代码,审查', '代码审查模板', '你是一个资深的代码审查专家。请对以下代码进行审查，指出问题并给出改进建议。

审查语言：{{language}}
审查重点：{{focus}}

代码：
{{code}}', 'language,focus,code', '{"temperature": 0.3}', '{}'),
(10003, 'translator', '翻译', '翻译专家模板', '你是一个专业的翻译专家，精通多种语言。请将以下文本翻译成目标语言。

源语言：{{source_lang}}
目标语言：{{target_lang}}

原文：{{text}}', 'source_lang,target_lang,text', '{"temperature": 0.3}', '{}'),
(10004, 'conversational_ai', 'chat,dialogue', '对话式AI模板', '你是一个{{role}}，具有以下特点：
{{personality}}

在与用户对话时，请遵循以下原则：
1. {{principle_1}}
2. {{principle_2}}
3. {{principle_3}}

用户：{{user_input}}

请回复：', 'role,personality,principle_1,principle_2,principle_3,user_input', '{"temperature": 0.7, "maxTokens": 2000}', '{}'),
(10005, 'social_media_promotion', 'social,promotion', '社交媒体推销文案生成模板', '你是一个擅长撰写社交媒体文案的 AI 助手，请根据提供的产品信息生成一条适合发布在{{platform}}平台的推广文案。

要求：
1. 使用轻松、亲切的口吻，像朋友分享好物；
2. 结尾添加相关话题标签，如 #好物推荐；

产品信息：
{{product_info}}', 'platform,product_info', '{"temperature": 0.8, "maxTokens": 500}', '{}'),
(10006, 'product_promotion', 'goods,promotion', '商品推广Prompt模板', '请为以下商品写一段推广文案：

商品名称：{{product_name}}
商品特点：{{features}}
目标人群：{{target_audience}}

要求：
1. 突出商品卖点
2. 语言简洁有力
3. 吸引目标人群购买', 'product_name,features,target_audience', '{"temperature": 0.7, "maxTokens": 300}', '{}'),
(10007, 'task_executor', 'task,execution', '任务执行模板', '你是一个专业的{{domain}}专家，请完成以下任务：

## 任务描述
{{task_description}}

## 输入信息
{{input_data}}

## 输出要求
{{output_requirements}}

## 约束条件
{{constraints}}

请按要求完成任务：', 'domain,task_description,input_data,output_requirements,constraints', '{"temperature": 0.3, "maxTokens": 3000}', '{}'),
(10008, 'analysis_report', 'analysis,report', '分析报告模板', '请对以下{{analysis_subject}}进行深入分析：

## 分析对象
{{subject_details}}

## 分析维度
{{analysis_dimensions}}

## 参考标准
{{reference_standards}}

## 报告结构
1. 摘要
2. 详细分析
3. 关键发现
4. 结论和建议

请生成完整的分析报告：', 'analysis_subject,subject_details,analysis_dimensions,reference_standards', '{"temperature": 0.4, "maxTokens": 4000}', '{}'),
(10009, 'creative_generator', 'creative,generation', '创意生成模板', '请为{{project_type}}项目生成创意方案：

## 项目背景
{{background}}

## 目标群体
{{target_audience}}

## 核心需求
{{core_requirements}}

## 创意约束
{{creative_constraints}}

## 输出要求
- 提供3-5个不同的创意方向
- 每个方向包含核心概念和执行要点
- 评估可行性和预期效果

请开始生成创意：', 'project_type,background,target_audience,core_requirements,creative_constraints', '{"temperature": 0.9, "maxTokens": 3000}', '{}'),
(10010, 'problem_solver', 'problem,solution', '问题解决模板', '作为{{expert_role}}，请帮助解决以下问题：

## 问题描述
{{problem_description}}

## 现状分析
{{current_situation}}

## 已尝试方案
{{attempted_solutions}}

## 限制条件
{{limitations}}

## 解决方案要求
1. 分析问题根因
2. 提供多个可选方案
3. 评估方案的可行性和风险
4. 推荐最优方案和实施步骤

请提供解决方案：', 'expert_role,problem_description,current_situation,attempted_solutions,limitations', '{"temperature": 0.5, "maxTokens": 3500}', '{}'),
(10011, 'teaching_assistant', 'education,teaching', '教学辅导模板', '你是一位经验丰富的{{subject}}老师，请为学生提供学习指导：

## 学生信息
- 学习水平：{{student_level}}
- 学习目标：{{learning_goal}}

## 教学内容
{{teaching_content}}

## 学生问题
{{student_question}}

## 教学要求
1. 用简单易懂的语言解释
2. 提供具体的例子
3. 给出练习建议
4. 鼓励学生思考

请开始教学：', 'subject,student_level,learning_goal,teaching_content,student_question', '{"temperature": 0.6, "maxTokens": 2500}', '{}'),
(10012, 'content_writer', '写作,内容创作', '内容创作专家模板，适用于文章、博客、营销文案等场景', '你是一位资深的内容创作专家，擅长撰写各类文体。请根据以下要求创作内容。

内容类型：{{content_type}}
目标受众：{{target_audience}}
风格要求：{{style}}
主题：{{topic}}

请直接输出内容：', 'content_type,target_audience,style,topic', '{"temperature": 0.8}', '{}'),
(10013, 'data_analyst', '数据分析', '数据分析专家模板，适用于数据解读、报表分析、趋势预测等场景', '你是一位专业的数据分析师。请根据以下数据和问题进行分析。

数据描述：{{data_description}}
分析目标：{{analysis_goal}}
数据样本：
{{data_sample}}

请提供分析结论和建议：', 'data_description,analysis_goal,data_sample', '{"temperature": 0.3}', '{}'),
(10014, 'customer_service', '客服', '智能客服模板，适用于售前咨询、售后支持、投诉处理等场景', '你是一位专业的客服代表，态度友好、耐心细致。请根据以下信息回复客户。

客服角色：{{service_role}}
客户问题：{{customer_issue}}
产品信息：{{product_info}}
回复语言：{{reply_lang}}

请给出专业回复：', 'service_role,customer_issue,product_info,reply_lang', '{"temperature": 0.5}', '{}'),
(10015, 'summarizer', '摘要,总结', '文本摘要专家模板，适用于长文摘要、会议纪要、报告精简等场景', '你是一位文本摘要专家。请对以下内容进行精准概括。

摘要类型：{{summary_type}}
摘要长度：{{summary_length}}
原文：
{{original_text}}

请输出摘要：', 'summary_type,summary_length,original_text', '{"temperature": 0.3}', '{}'),
(10016, 'email_composer', '邮件', '邮件撰写专家模板，适用于商务邮件、工作汇报、客户沟通等场景', '你是一位专业的邮件撰写助手。请根据以下信息撰写邮件。

邮件场景：{{scenario}}
收件人：{{recipient}}
邮件目的：{{purpose}}
关键要点：{{key_points}}
语气：{{tone}}

请输出完整邮件（含主题行）：', 'scenario,recipient,purpose,key_points,tone', '{"temperature": 0.6}', '{}');

-- ============================================================================
-- Source: 2026-06-19-001.sql
-- ============================================================================

-- 评估器表新增 tags 字段
ALTER TABLE eval_evaluator ADD COLUMN tags VARCHAR(200);
COMMENT ON COLUMN eval_evaluator.tags IS '标签，逗号分隔';

-- 实验结果表新增 evaluator_name 字段
ALTER TABLE eval_experiment_result ADD COLUMN evaluator_name VARCHAR(128);
COMMENT ON COLUMN eval_experiment_result.evaluator_name IS '评估器名称';

-- ============================================================================
-- Source: 2026-06-22-001.sql
-- ============================================================================

-- 工具表新增 output_example 列，存储输出示例 JSON
ALTER TABLE tool ADD COLUMN output_example JSONB DEFAULT '{}';

-- ============================================================================
-- Source: 2026-06-22-002.sql
-- ============================================================================

-- SubAgent: tools 已合并为 tool_ids（见上方 CREATE TABLE subagent）

-- ============================================================================
-- Source: 2026-06-24-001.sql
-- ============================================================================

-- Message 表重构：移除废弃字段，新增 message_type 字段
-- 1. 删除 tool_calls 和 tool_call_id 列（从未使用）
-- 2. 新增 message_type 列（text / multimodal_image）

ALTER TABLE message DROP COLUMN IF EXISTS tool_calls;
ALTER TABLE message DROP COLUMN IF EXISTS tool_call_id;

ALTER TABLE message ADD COLUMN IF NOT EXISTS message_type VARCHAR(32) NOT NULL DEFAULT 'text';

COMMENT ON COLUMN message.message_type IS '消息类型：text-文本, multimodal_image-多模态图片';

-- ============================================================================
-- Source: 2026-06-24-002.sql
-- ============================================================================

-- 删除 Skill 表废弃字段 tool_id（已被 tool_ids JSONB 数组取代）
ALTER TABLE skill DROP COLUMN IF EXISTS tool_id;
DROP INDEX IF EXISTS idx_skill_tool_id;

-- ============================================================================
-- Source: 2026-06-25-001.sql
-- ============================================================================

-- 合并 CUSTOM 类型到 API
UPDATE tool SET tool_type = 'API' WHERE tool_type = 'CUSTOM';

-- 删除 MCP 类型的工具（MCP 管理已独立为 McpServer 模块）
DELETE FROM tool WHERE tool_type = 'MCP';

-- ============================================================================
-- Source: 2026-06-25-002.sql
-- ============================================================================

-- chat_session 表新增 agent_version_id 列，记录会话最近使用的 Agent 版本快照 ID
-- 使用 agent_version.id（主键）而非 version 编号，避免版本删除后编号复用导致误匹配
ALTER TABLE chat_session ADD COLUMN agent_version_id BIGINT;
COMMENT ON COLUMN chat_session.agent_version_id IS '最近使用的Agent版本快照ID（agent_version.id），null=未指定';

-- ============================================================================
-- Source: 2026-06-25-003.sql
-- ============================================================================

-- 消息表新增 reply_to_message_id 字段，支持引用回复
ALTER TABLE message ADD COLUMN reply_to_message_id BIGINT;

-- ============================================================================
-- Source: 2026-06-25-004.sql
-- ============================================================================

-- API Key 管理表
CREATE TABLE api_key (
    id              BIGINT          NOT NULL,
    user_id         BIGINT          NOT NULL,
    name            VARCHAR(64)     NOT NULL,
    key_prefix      VARCHAR(20)     NOT NULL,
    key_hash        VARCHAR(64)     NOT NULL,
    permissions     VARCHAR(32)     NOT NULL DEFAULT 'chat',
    is_enabled      SMALLINT        NOT NULL DEFAULT 1,
    last_used_at    TIMESTAMP       NULL,
    expires_at      TIMESTAMP       NULL,
    create_time     TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time     TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted         SMALLINT        NOT NULL DEFAULT 0,
    PRIMARY KEY (id)
);
CREATE INDEX idx_api_key_user_id ON api_key (user_id);
CREATE UNIQUE INDEX uk_api_key_hash ON api_key (key_hash);
COMMENT ON TABLE api_key IS 'API Key管理表';

-- ============================================================================
-- Source: 2026-06-25-005.sql
-- ============================================================================

-- RAG 检索反馈表：用户对 RAG 引用的有用/无用反馈
CREATE TABLE rag_feedback (
    id              BIGINT          NOT NULL,
    message_id      BIGINT          NOT NULL,
    user_id         BIGINT          NOT NULL,
    chunk_id        BIGINT,
    qa_pair_id      BIGINT,
    source_type     VARCHAR(20)     NOT NULL,
    feedback_type   VARCHAR(20)     NOT NULL,
    create_time     TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);
CREATE INDEX idx_rag_feedback_message ON rag_feedback (message_id);
CREATE INDEX idx_rag_feedback_user ON rag_feedback (user_id);
COMMENT ON TABLE rag_feedback IS 'RAG检索反馈表';

-- ============================================================================
-- Source: 2026-06-25-006.sql
-- ============================================================================

-- 子代理运行记录表（运行追踪 + 幂等性 + 批次委派）
CREATE TABLE subagent_run (
    id                  BIGINT          NOT NULL,
    thread_id           VARCHAR(100)    NOT NULL,
    parent_thread_id    VARCHAR(100)    NOT NULL,
    subagent_name       VARCHAR(100)    NOT NULL,
    task                TEXT            NOT NULL,
    status              VARCHAR(20)     NOT NULL DEFAULT 'pending',
    request_id          VARCHAR(64)     NOT NULL,
    batch_id            VARCHAR(80),
    parent_request_id   VARCHAR(100),
    parent_session_id   BIGINT,
    mode                VARCHAR(20)     NOT NULL DEFAULT 'sync',
    cancel_requested    SMALLINT        NOT NULL DEFAULT 0,
    reply               TEXT,
    tool_call_count     INTEGER         DEFAULT 0,
    start_time          TIMESTAMP,
    end_time            TIMESTAMP,
    error_message       TEXT,
    create_time         TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time         TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);
CREATE UNIQUE INDEX idx_subagent_run_request_id ON subagent_run(request_id);
CREATE INDEX idx_subagent_run_thread_id ON subagent_run(thread_id);
CREATE INDEX idx_subagent_run_batch_id ON subagent_run(batch_id);
CREATE INDEX idx_subagent_run_parent_request ON subagent_run(parent_request_id);
CREATE INDEX idx_subagent_run_status ON subagent_run(status);
COMMENT ON TABLE subagent_run IS 'SubAgent 运行记录表';
COMMENT ON COLUMN subagent_run.batch_id IS 'SubAgent 委派批次ID';
COMMENT ON COLUMN subagent_run.parent_request_id IS '父 Agent 请求ID';
COMMENT ON COLUMN subagent_run.parent_session_id IS '父 Agent 会话ID';
COMMENT ON COLUMN subagent_run.mode IS '委派模式：sync/parallel';
COMMENT ON COLUMN subagent_run.cancel_requested IS '是否请求取消：0否 1是';

-- ============================================================================
-- Source: 2026-06-25-007.sql
-- ============================================================================

-- MCP Server 新增最后同步时间字段
ALTER TABLE mcp_server ADD COLUMN last_sync_time TIMESTAMP;
COMMENT ON COLUMN mcp_server.last_sync_time IS '最后一次工具列表同步时间';

-- ============================================================================
-- Source: 2026-06-25-008.sql
-- ============================================================================

-- 消息收藏功能：message 表新增 starred 字段
ALTER TABLE message ADD COLUMN starred BOOLEAN NOT NULL DEFAULT FALSE;
CREATE INDEX idx_message_starred ON message (starred) WHERE starred = TRUE;
COMMENT ON COLUMN message.starred IS '是否收藏';

-- ============================================================================
-- Source: 2026-06-26-001.sql
-- ============================================================================

-- 消息反馈表：用户对 AI 回复消息的点赞/踩反馈
CREATE TABLE message_feedback (
    id              BIGINT          NOT NULL,
    message_id      BIGINT          NOT NULL,
    user_id         BIGINT          NOT NULL,
    rating          VARCHAR(10)     NOT NULL,
    reason          TEXT,
    agent_id        BIGINT,
    agent_version   INT,
    create_time     TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

-- 唯一索引：每人每条消息只能有一条反馈
CREATE UNIQUE INDEX uk_message_feedback_user_message ON message_feedback (user_id, message_id);
CREATE INDEX idx_message_feedback_message_id ON message_feedback (message_id);
CREATE INDEX idx_message_feedback_agent_id ON message_feedback (agent_id);

COMMENT ON TABLE message_feedback IS '消息反馈表';
COMMENT ON COLUMN message_feedback.id IS '主键ID';
COMMENT ON COLUMN message_feedback.message_id IS '消息ID';
COMMENT ON COLUMN message_feedback.user_id IS '用户ID';
COMMENT ON COLUMN message_feedback.rating IS '评分：like/dislike';
COMMENT ON COLUMN message_feedback.reason IS '反馈原因（dislike时可选填写）';
COMMENT ON COLUMN message_feedback.agent_id IS '所属Agent ID（反馈提交时快照）';
COMMENT ON COLUMN message_feedback.agent_version IS 'Agent版本号（反馈提交时快照，0=草稿）';
COMMENT ON COLUMN message_feedback.create_time IS '创建时间';

-- ============================================================================
-- Source: 2026-06-26-002.sql
-- ============================================================================

-- 删除旧的 RAG 反馈表（已由 message_feedback 表替代）
DROP TABLE IF EXISTS rag_feedback;

-- ============================================================================
-- Source: 2026-06-26-003.sql
-- ============================================================================

-- API Key 增强：限流、作用域、配额
ALTER TABLE api_key ADD COLUMN agent_ids JSONB DEFAULT NULL;
ALTER TABLE api_key ADD COLUMN rate_limit INT NOT NULL DEFAULT 60;
ALTER TABLE api_key ADD COLUMN daily_quota INT NOT NULL DEFAULT 100000;
ALTER TABLE api_key ADD COLUMN used_tokens BIGINT NOT NULL DEFAULT 0;
ALTER TABLE api_key ADD COLUMN quota_reset_at DATE DEFAULT NULL;
ALTER TABLE api_key ADD COLUMN IF NOT EXISTS memory_config JSONB;
COMMENT ON COLUMN api_key.memory_config IS '长期记忆策略覆盖；null 或 inherit=true 跟随企业默认';

COMMENT ON COLUMN api_key.agent_ids IS '绑定的Agent ID列表，null表示全部';
COMMENT ON COLUMN api_key.rate_limit IS '每分钟调用上限，默认60';
COMMENT ON COLUMN api_key.daily_quota IS '每日Token配额，默认100000';
COMMENT ON COLUMN api_key.used_tokens IS '当日已用Token数';
COMMENT ON COLUMN api_key.quota_reset_at IS '配额重置日期（每日重置时比较）';

-- ============================================================================
-- Source: 2026-07-14-001.sql
-- ============================================================================

-- MCP Server 增加平台内置标识，并回填历史内置 MCP。
ALTER TABLE mcp_server
    ADD COLUMN IF NOT EXISTS is_builtin SMALLINT NOT NULL DEFAULT 0;

CREATE INDEX IF NOT EXISTS idx_mcp_server_is_builtin ON mcp_server (is_builtin);

COMMENT ON COLUMN mcp_server.is_builtin IS '是否平台内置：1=是，0=否';

UPDATE mcp_server
SET is_builtin = 1
WHERE (name = 'mcp-server-chart'
       AND install_type = 'npx'
       AND COALESCE(deploy_config ->> 'packageName', '') = '@antv/mcp-server-chart')
   OR (name = 'sequentialthinking'
       AND host = 'https://remote.mcpservers.org/sequentialthinking/mcp');

-- ============================================================================
-- Source: 2026-07-18-001.sql
-- ============================================================================

-- Redis Stream 任务队列：重试、延迟队列和死信字段。
ALTER TABLE task ADD COLUMN IF NOT EXISTS attempts SMALLINT NOT NULL DEFAULT 0;
ALTER TABLE task ADD COLUMN IF NOT EXISTS max_attempts SMALLINT NOT NULL DEFAULT 3;
ALTER TABLE task ADD COLUMN IF NOT EXISTS next_retry_at TIMESTAMP;
ALTER TABLE task ADD COLUMN IF NOT EXISTS stream_id VARCHAR(40);
ALTER TABLE task ADD COLUMN IF NOT EXISTS dead_letter SMALLINT NOT NULL DEFAULT 0;

COMMENT ON COLUMN task.attempts IS '已尝试次数（含首次执行）';
COMMENT ON COLUMN task.max_attempts IS '最大尝试次数（含首次执行）';
COMMENT ON COLUMN task.next_retry_at IS '下次重试时间，NULL 表示无延迟重试';
COMMENT ON COLUMN task.stream_id IS 'Redis Stream 消息 ID';
COMMENT ON COLUMN task.dead_letter IS '是否已转入死信 Stream：0=否，1=是';

CREATE INDEX IF NOT EXISTS idx_task_next_retry
    ON task (next_retry_at)
    WHERE next_retry_at IS NOT NULL AND deleted = 0;

CREATE INDEX IF NOT EXISTS idx_task_dead_letter
    ON task (dead_letter)
    WHERE dead_letter = 1 AND deleted = 0;

ALTER TABLE subagent ALTER COLUMN read_timeout_seconds SET DEFAULT 60;
UPDATE subagent SET read_timeout_seconds = 60 WHERE is_builtin = 1 AND read_timeout_seconds = 30;

-- ============================================================================
-- Source: 2026-07-18-002.sql
-- ============================================================================

-- 工具事件与消息 metadata 解耦，避免前端深度监听扫描大对象。
ALTER TABLE message ADD COLUMN IF NOT EXISTS tool_events JSONB DEFAULT '[]';
COMMENT ON COLUMN message.tool_events IS '工具事件流（tool_call、tool_result、subagent_* 等），与 metadata 解耦存储';

-- ============================================================================
-- Source: 2026-07-20-001.sql and 2026-07-20-002.sql
-- ============================================================================

-- RAG 引用、反馈和请求 ID 查询索引。
CREATE INDEX IF NOT EXISTS idx_message_metadata_gin ON message USING GIN (metadata jsonb_path_ops);
CREATE INDEX IF NOT EXISTS idx_message_rag_refs
    ON message USING GIN ((metadata -> 'ragReferences') jsonb_path_ops);
CREATE INDEX IF NOT EXISTS idx_message_feedback_msg_rating
    ON message_feedback (message_id, rating);
CREATE INDEX IF NOT EXISTS idx_message_metadata_request_id
    ON message ((metadata ->> 'requestId'))
    WHERE metadata ? 'requestId';

-- 允许 SubAgent 软删除后以同名重新创建。
ALTER TABLE subagent DROP CONSTRAINT IF EXISTS subagent_name_key;
DROP INDEX IF EXISTS idx_subagent_name;
CREATE UNIQUE INDEX IF NOT EXISTS uk_subagent_name_alive
    ON subagent (name)
    WHERE deleted = 0;

-- ============================================================================
-- Source: 2026-07-21-001.sql
-- ============================================================================

-- 工具维度限流配置：{"limit": 10, "window": "MINUTE|HOUR|DAY"}。
ALTER TABLE tool ADD COLUMN IF NOT EXISTS rate_limit_enabled BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE tool ADD COLUMN IF NOT EXISTS rate_limit_config JSONB;
COMMENT ON COLUMN tool.rate_limit_enabled IS '是否启用限流';
COMMENT ON COLUMN tool.rate_limit_config IS '限流配置 JSON：limit/window';
